{% set version = "1.14.1" %}
{% set sha256 = "28d82b0d261544a9bf85b429399929e4986eb00efcf1ce16cc71d269a4c3186c" %}

package:
  name: gstreamer
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  script: install_gstreamer.sh
  # activate_in_script: True
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gstreamer', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - bison
    - flex
    - m4
    - autoconf
    - automake
    - make
    - perl
  host:
    - gobject-introspection
    - gettext                            # [osx]
    - pcre                               # [linux]
    - libffi                             # [linux]
    - glib
    - xz

test:
  commands:
    - gst-inspect-1.0 --version
    - gst-launch-1.0  --version
    - gst-stats-1.0 --version
    - gst-typefind-1.0 --version

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL 2
  summary: "Library for constructing graphs of media-handling components"

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
