{% set version = "1.8.3" %}
{% set sha256 = "66b37762d4fdcd63bce5a2bec57e055f92420e95037361609900278c0db7c53f" %}

package:
  name: gstreamer
  version: {{ version }}

source:
  fn: gstreamer-{{ version }}.tar.xz
  url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  skip: true  # [win or osx]
  number: 0

requirements:
  build:
    - bison
    - flex
    - glib 2.51.*
    - m4
    - perl
    - xz 5.2.*
  run:
    - glib 2.51.*

test:
  commands:
    - gst-inspect-1.0 --version
    - gst-launch-1.0  --version
    - gst-stats-1.0 --version
    - gst-typefind-1.0 --version

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL 2
  summary: "Library for constructing graphs of media-handling components"

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
