build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
  osx_arm64: github_actions
test: native_and_emulated
conda_build_tool: rattler-build
conda_install_tool: pixi
github_actions:
  self_hosted: true
  timeout_minutes: 360
  triggers:
    - push
    - pull_request
